# configuration file for dotnet-releaser
profile = "custom"
[msbuild]
project = "sumohelp.csproj"
[github]
user = "Soulsbane"
repo = "sumohelp"

# Default values used by `dotnet-releaser`
[msbuild.properties]
PublishTrimmed = false
PublishSingleFile = true
SelfContained = true
PublishReadyToRun = true
CopyOutputSymbolsToPublishDirectory = false
SkipCopyingSymbolsToOutputDirectory = true
PackAsTool = false
[nuget]
publish = false

[changelog]
publish = true

[[pack]]
rid = ["win-x64"]
kinds = ["zip"]

[[pack]]
rid = ["linux-x64"]
kinds = ["tar"]

[[pack]]
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]
